# Custom quest, ID: 4004

title = "The Headless Horseman Has Hellish Hobbies"
npc = "Legor [Leafre: Forest of the Priest]"
info = """
So I'm... sure that you've heard of the #eHaunted Mansion#n. Heck, you've probably been there yourself. Seems a bit spooky, but innocent enough.

There is one hell of a bunch of wacky-ass creatures living there; but if you go too deep, you'll find there's something much more sinister lurking in there.

I'm not talking about the #eHeadless Horseman#n or the #eSasquatch#n around there, oh no. Those two hardly pose danger compared to what's deep in there, in the forest of dead trees and lost souls.

You see, somewhere around 230 years or so ago, we had to put a stopper on that whole place or this entire continent was going to be hell-on-earth-spooksville. So we found one big guy we could... sort of count on. The #eHeadless Horseman#n. We were able to let him... um... pursue his "hobbies" so long as he protected us from the inside of the dead forest.

The problem is, sometimes he just gets a bit #etoo#n out of control. So we need you to take him down a few notches, and bring us back six Jack O'Lanterns to prove it."""


[requirements]
quests = [4000, 4001, 4002, 4003]
predicates = [
    """
    var rewardSkills =
    [
        [1320006, 30], [1221004, 20],
        [1121010, 20]
    ];

    function(p) {
        var rewardSkill;
        for (var i = 0; i < rewardSkills.length; ++i) {
            if (Math.floor(rewardSkills[i][0] / 10000) === p.getJob().getId()) {
                rewardSkill = rewardSkills[i];
                break;
            }
        }
        return rewardSkill !== undefined && p.getMasterLevelById(rewardSkill[0]) >= rewardSkill[1] - 10;
    }
    """
]


[[monsters]]
id = 9400549
name = "Headless Horseman"
count = 6


[[items]]
id = 4031903
name = "Jack O'Lantern"
count = 6


[par]
fearless = 99
valiant = 121
adventuresome = 141


[rewards]
exp = 7189000
mesos = 175000
    [[rewards.items]]
    id = 4001126
    count = 8
consumers = [
    """
    var rewardSkills =
    [
        [1320006, 30], [1221004, 20],
        [1121010, 20]
    ];

    function(p) {
        var reward;
        for (var i = 0; i < rewardSkills.length; ++i) {
            if (Math.floor(rewardSkills[i][0] / 10000) === p.getJob().getId()) {
                reward = rewardSkills[i];
                p.setMasterLevel(reward[0], reward[1]);
                break;
            }
        }
        if (reward[0] === 1221004) {
            p.setMasterLevel(reward[0] - 1, reward[1]);
        } else if (reward[0] === 1121010) {
            p.setMasterLevel(reward[0], reward[1] + 10);
        }
    }
    """
]
