# Custom quest, ID: 6000

title = "Got Golems, Gather Good Guys"
npc = "Samuel [Leafre: Forest of the Priest]"
info = """
Alright, kid. So you wanna summon monsters and constructs to fight for you?

Well tough shit. You don't know the first thing about constructs. Do you even know what that word means? I doubt it.

Look, if you wanna summon sweet-ass golems and octopoes 'n' shit like me, you're gonna have to slay a few constructs yourself so you can know how they work. You know, what they're made of, what makes 'em tick.

That's why I'm sending out out to gather for me #b80 Yellow Toy Blocks#k, #b80 Blue Toy Blocks#k, #b80 Destroyed Nests#k, #b80 Stone Golem Rubbles#k, #b80 Dark Stone Golem Rubbles#k, and #b80 Mixed Blocks#k."""


[requirements]
predicates = [
    """
    var rewardSkills =
    [
        [3121006, 30], [3221005, 30],
        [2321003, 20], [2221005, 30],
        [2121005, 30], [5220002, 20],
        [1320008, 25]
    ];

    function(p) {
        var rewardSkill;
        for (var i = 0; i < rewardSkills.length; ++i) {
            if (Math.floor(rewardSkills[i][0] / 10000) === p.getJob().getId()) {
                rewardSkill = rewardSkills[i];
                break;
            }
        }
        return rewardSkill !== undefined && p.getMasterLevelById(rewardSkill[0]) >= rewardSkill[1] - 10;
    }
    """
]


[[monsters]]
id = 8190002
name = "Nest Golem"
count = 50

[[monsters]]
id = 5150000
name = "Mixed Golem"
count = 80


[[items]]
id = 4000101
name = "Yellow Toy Block"
count = 80

[[items]]
id = 4000102
name = "Blue Toy Block"
count = 80

[[items]]
id = 4000271
name = "Destroyed Nest"
count = 80

[[items]]
id = 4000022
name = "Stone Golem Rubble"
count = 80

[[items]]
id = 4000025
name = "Dark Stone Golem Rubble"
count = 80

[[items]]
id = 4000177
name = "Mixed Block"
count = 80


[par]
fearless = 108
valiant = 130
adventuresome = 145


[rewards]
exp = 8653000
mesos = 120000
    [[rewards.items]]
    id = 4001126
    count = 7
consumers = [
    """
    var rewardSkills =
    [
        [3121006, 30], [3221005, 30],
        [2321003, 20], [2221005, 30],
        [2121005, 30], [5220002, 20],
        [1320008, 25]
    ];

    function(p) {
        var reward;
        for (var i = 0; i < rewardSkills.length; ++i) {
            if (Math.floor(rewardSkills[i][0] / 10000) === p.getJob().getId()) {
                reward = rewardSkills[i];
                p.setMasterLevel(reward[0], reward[1]);
                break;
            }
        }
        if (reward[0] === 2321003) {
            p.setMasterLevel(reward[0], reward[1] + 10);
        } else if (reward[0] === 1320008) {
            p.setMasterLevel(reward[0] + 1, reward[1]);
        }
    }
    """
]
